version: '3.8'

services:
  mysql:
    container_name: mysql_local
    image: mysql:8.0.30
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=module_local
      - MYSQL_USER=module_local_user
      - MYSQL_PASSWORD=modulelocal123
      - MYSQL_ROOT_PASSWORD=modulelocal123
      - TZ=Asia/Seoul
